# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRccToWQ_6DDqpy-S7c6nUAut0KsWPPh
"""

def GCD(a,b):
  if b==0:
    return a

  return GCD(b,a % b)



def LCM(a,b):
  X=GCD(a,b)
  return(a*b)/X
print(LCM(36,48))